@startuml
!define RECTANGLE_CLASS
!define RECTANGLE_BLUE Class<<BLUE>>

skinparam shadowing false
skinparam backgroundColor #FFFFFF
skinparam ArrowColor #0000FF
skinparam activity {
    BackgroundColor<<BLUE>> #ADD8E6
    BorderColor<<BLUE>> #00008B
    FontColor<<BLUE>> #00008B
    FontSize 12
}
skinparam class {
    BackgroundColor #FEFECE
    BorderColor #B8860B
    ArrowColor #B8860B
    FontSize 12
    FontName Arial
}
skinparam usecase {
    BackgroundColor #FFFFA3
    BorderColor #FFA500
    FontSize 12
    FontName Arial
}
skinparam package {
    BackgroundColor #FFFFFF
    BorderColor #B8860B
    FontSize 12
    FontName Arial
}
skinparam participant {
    BackgroundColor #B0E0E6
    BorderColor #4682B4
    FontSize 12
    FontName Arial
}

actor User
entity Web
entity LottoModule
database Database


== Exchange ticket point with reward points ==

User -[#0000FF]> Web : request to exchange reward points \nfor ticket point.
Web --> User: point exchange page is exposed.
User -[#0000FF]> Web : exchange
Web -[#0000FF]> LottoModule: exchange

activate LottoModule
LottoModule --[#0000FF]> LottoModule : verifies the user's reward points.


LottoModule -[#0000FF]-> LottoModule : exchange.
note left: exchange points according to the ratio \nof reward points and ticket points.
LottoModule --> Database : updates the status of the user's reward points \nand transactions.

deactivate LottoModule


@enduml
