@startuml
!define RECTANGLE_CLASS
!define RECTANGLE_BLUE Class<<BLUE>>

skinparam shadowing false
skinparam backgroundColor #FFFFFF
skinparam ArrowColor #0000FF
skinparam activity {
    BackgroundColor<<BLUE>> #ADD8E6
    BorderColor<<BLUE>> #00008B
    FontColor<<BLUE>> #00008B
    FontSize 12
}
skinparam class {
    BackgroundColor #FEFECE
    BorderColor #B8860B
    ArrowColor #B8860B
    FontSize 12
    FontName Arial
}
skinparam usecase {
    BackgroundColor #FFFFA3
    BorderColor #FFA500
    FontSize 12
    FontName Arial
}
skinparam package {
    BackgroundColor #FFFFFF
    BorderColor #B8860B
    FontSize 12
    FontName Arial
}
skinparam participant {
    BackgroundColor #B0E0E6
    BorderColor #4682B4
    FontSize 12
    FontName Arial
}


actor User
participant "Next.js SSG" as SSG
participant "AWS CloudFront" as CF
participant "AWS S3" as S3
participant "API Server (EC2)" as EC2
participant "Database (RDS)" as RDS

User -> CF : Request Page
CF -> S3 : Fetch Static Page
S3 -> CF : Return Static Page
CF -> User : Deliver Static Page

User -> SSG : Trigger Event (e.g., Button Click)
SSG -> EC2 : Send HTTP Request (e.g., POST /update)
EC2 -> EC2 : Process Request
EC2 -> RDS : Update Database
RDS -> EC2 : Return Success Response
EC2 -> SSG : Send HTTP Response
SSG -> User : Update UI (if needed)

@enduml
